
version: '3'

services:
  mongo-express:
    depends_on: 
      - mongo
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge