import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import {
  DragDropContext,
  Draggable,
  Droppable,
  DropResult,
  ResponderProvided,
} from "react-beautiful-dnd";
import { useCallback } from "react";

const dragItems = Array.from({ length: 20 }).map((_, index) => ({
  id: `${index}-item`,
  content: "Item " + index,
}));

export default function Home() {
  const handleDragEnd = useCallback(
    (result: DropResult, provided: ResponderProvided) => {
      console.log({ result, provided });
    },
    []
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>AQUI</h1>
        <DragDropContext onDragEnd={handleDragEnd}>
          <Droppable droppableId="list">
            {({ innerRef, droppableProps, placeholder }) => (
              <ul className="list" {...droppableProps} ref={innerRef}>
                {dragItems.map((el, index) => (
                  <Draggable key={el.id} draggableId={el.id} index={index}>
                    {({ innerRef, dragHandleProps, draggableProps }) => (
                      <li
                        ref={innerRef}
                        {...draggableProps}
                        {...dragHandleProps}
                      >
                        <div>{el.content}</div>
                      </li>
                    )}
                  </Draggable>
                ))}
                {placeholder}
              </ul>
            )}
          </Droppable>
        </DragDropContext>
      </main>
    </>
  );
}
